name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'docker/buildx/**.Dockerfile'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-7
          - centos-8
          - ubuntu-2004
          - ubuntu-2204
          - ubuntu-2404
    steps:
    - name: Setup environment variables
      id: vars
      run: |
        echo "TAG=$(echo ${{ matrix.os }} | tr -d '-')" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/build-push-action@v6
      with:
        context: .
        file: ./docker/buildx/${{ matrix.os }}.Dockerfile
        platforms: linux/amd64,linux/arm64
        tags: vesoft/third-party-build:${{ steps.vars.outputs.TAG }}
        push: true
